### ISSUE TITLE
Output of test 5.1.1

### ISSUE THREAD

**Issue by moalaa** [tingyuw/cas741#10]
@tingyuw, In this testcase are you just trying to check that the output file will be generated, or the contents of this file?
Also, can you specify the extension of this output file, or it is not a big deal? 
![issue2](https://user-images.githubusercontent.com/31176105/98154790-4caf6e00-1ea3-11eb-87c1-d6cfe16ce3c9.PNG)

**Comment by tingyuw** [comment]
I will check the output values. I reference the output correctness test to verify the outputs.
And I included the file type, thank you!

![image](https://user-images.githubusercontent.com/47548045/101593693-5b1b0900-39be-11eb-97e6-2405f84bbc1e.png)
