### ISSUE TITLE
How test will be performed

### ISSUE THREAD

**Issue by moalaa** [tingyuw/cas741#11]
@tingyuw, I believe you should add more details about how the test will be performed I know you will use **PyUnit** as **unit testing** but you can add more information in your tests to make it clear. :smile:
![issue3](https://user-images.githubusercontent.com/31176105/98154794-4f11c800-1ea3-11eb-8ed1-819f11ee2f5f.PNG)

**Comment by tingyuw** [comment]
I addressed this problem in 2d596d832f7490ea524e401291526d3692ce603e.
If it is still not clear please let me know : )
