### ISSUE TITLE
Validation Plan

### ISSUE THREAD

**Issue by moalaa** [tingyuw/cas741#12]
Hu @tingyuw, I think Dr. @smiths mentioned that the correctness of the outputs doesn't mean the software is fully tested or validated. Can you add more details in this section about your validation plan?
![issue4](https://user-images.githubusercontent.com/31176105/98154801-520cb880-1ea3-11eb-92f7-afbd5c4b7ebb.PNG)

**Comment by tingyuw** [comment]
Actually I think there is no validation step of my project since there is no experimental data to compare with. It is updated in 8ba98fdfb41fc2065134e47af0caecd4db202a39. Thank you for the comment!
