### ISSUE TITLE
References

### ISSUE THREAD

**Issue by moalaa** [tingyuw/cas741#13]
Hello @tingyuw,
I think you can increase the number of the references, for example, you can reference **Rubber Duck Testing**. :wink:

![issue55](https://user-images.githubusercontent.com/31176105/98155228-e37c2a80-1ea3-11eb-96cc-5b517544fc9e.PNG)

![issue5](https://user-images.githubusercontent.com/31176105/98154807-53d67c00-1ea3-11eb-9ee9-0575103dc5a3.PNG)

**Comment by tingyuw** [comment]
Thank you for the advice!
I addressed this with 2d596d832f7490ea524e401291526d3692ce603e.
