### ISSUE TITLE
VnV review - Section 5.1.1

### ISSUE THREAD

**Issue by machadotiagom** [tingyuw/cas741#19]
Hi @tingyuw 

In 5.1.1, I did not figure out how the input verification will be done I guess. Why did you provide specific and fixed values for the Force, Positioning and Angle? Would not be better if you test your input through a test bench so you can define the range of values for which your software should work well for all possible scenarios? For instance, in the "2 - Invalid distance", what happens if the user enters a positive value for x1 or x3, or a positive/negative value for x2?

Tiago.

**Comment by tingyuw** [comment]
What I meant was that other values should be valid and I changed only one component in each test case to test its verification. I admitted that It was not clear then. I addressed the problem by providing a test cases table in 3bd08f8e00b7c217a4d466ded79496a3341bff90. If it is still not clear please let me know.
