### ISSUE TITLE
About instance models

### ISSUE THREAD

**Issue by tingyuw** [tingyuw/cas741#2]
Hello Dr. Smith
I have some questions about what instance models should be in this project.
The key equations to solve the problem is ∑Fx=0 and ∑Fy=0. I need to implement these equations to every pin to find out all the forces of the truss members,. My first thought is taking these two equations as the IMs, but I'm still thinking how to take the other's output as an input and let the equation be more general to all truss problems. 
My second thought is doing it in a more specific way. For example, if I'm going to use the following truss problem as my example, I list all the equations as my IMs. Which are 3kN = Fa * sin(θ), Fb = Fe, and so on. 

![image](https://user-images.githubusercontent.com/47548045/94697882-b8337800-0306-11eb-81d2-e3b5a955bf45.png)
![image](https://user-images.githubusercontent.com/47548045/94697939-c386a380-0306-11eb-82a7-2bcf28d87fe9.png)

I was going to take these two equations as general definitions at first, but in this case the instance models could only be specific.

**Comment by smiths** [comment]
Thank you for the question @tingyuw.  You are off to a good start.  The example that is closest to yours is the beam problem, as done by Lei Lai.  You can find information on her specification in SmithLaiAndKhedri2007fulltex.pdf and SmithAndLai_2005.pdf.  (Remember electronic versions of almost all of my papers (and many others) are in the pub repo.)

You should pick a specific truss, just as Lei Lai picked a specific beam.  However, the inputs should not be prescribed in your SRS.  The forces should be variables, as should the dimensions.  You can look at Lei Lai's picture of her beam to see what I mean.

Your theoretical model is the same as Lei Lai's.  The sum of the forces in the x and y direction are zero AND the sum of the moments is zero.  (You need the last equation to find the support reactions.)

Your instance model will be the equations that you solve to find the specific forces.  The equations will take the general theoretical model and substitute in the symbols for the variables that define the truss.

**Comment by tingyuw** [comment]
Okay, I think I know how to do it. Thank you! @smiths
