### ISSUE TITLE
VnV review - Section 5.1.2

### ISSUE THREAD

**Issue by machadotiagom** [tingyuw/cas741#20]
Hi @tingyuw 

In 5.1.2, here the same rationale used for 5.1.1 applies. Would not be better the creation of a test bench to test all expected outcomes for a certain range of values? I do not think that the output can be evaluated by just providing a specific known unitary value at the input. If I am interpreting wrong this section, I might suggest you give us a bit of context by explaining what sort of conditions apply for those testing. :grin:

Still in 5.1.2, "2 - Correctness of output file", I did not understand what output file is the input for this testing, neither what sort of relative error you are looking for. What is the variable being considered here?

Tiago.

**Comment by tingyuw** [comment]
Other input sets can all be tested in the same way as provided in section 5.1.2.2. I'm not sure whether this is what you are asking. For your second question, I have added more details about it in 3bd08f8e00b7c217a4d466ded79496a3341bff90. If it is still not clear please let me know!
