### ISSUE TITLE
Author name missing in people.hs

### ISSUE THREAD

**Issue by andreamclemeno** [tingyuw/cas741#26]
Hi @tingyuw !

This may be a problem with the my version of your repo but it's not running for me due to this error. I am not sure why but it may just be for mine! Just in case you or anyone else has the same, I will mention it ![image](https://user-images.githubusercontent.com/70977402/100959081-851a8a00-34eb-11eb-97d8-5c0a39d65c9f.png)

I am guessing on mine that I don't have you in the people folder so I will just add that and see how it goes :)

Thanks,

Andrea

**Comment by smiths** [comment]
@tingyuw, I noticed the same problem in your repo.  I was able to fix it by adding you to the `People.hs` file in the folder `code/drasil-data/Data/Drasil`.  I tried to push the change to your repo, but I don't have permission to make changes to your repo, and I don't have time to set up a pull request.  :smile:

**Comment by tingyuw** [comment]
Sorry, I forgot to update related documents. people.hs is added in the repo!
