### ISSUE TITLE
Update the makefile in Repos/Drasil/code

### ISSUE THREAD

**Issue by andreamclemeno** [tingyuw/cas741#27]
Hi @tingyuw,

I found something similar with this part of your code. I am not sure if it's just in my cloned repo and you already updated it but when I ran it for your code, I didn't the .tex or .html file so I looked in your makefile in your code folder and your program wasn't added!

I think you are maybe only updating your new code like for your drasil-example/Truss folder for your program  So I think you should update all files and I think it should work 👍 

Thanks,

Andrea

**Comment by smiths** [comment]
I noticed this problem too @tingyuw when I was looking for your generated SRS for comments.  Instead of the truss folder in the build folder, the generated files are going into the code folder.

**Comment by tingyuw** [comment]
Thank you for the comment. All related documents are updated!
