### ISSUE TITLE
Update code/datafiles folder

### ISSUE THREAD

**Issue by andreamclemeno** [tingyuw/cas741#28]
Hi @tingyuw !

I think similar idea here. The program is running but giving me this: 

![image](https://user-images.githubusercontent.com/70977402/100961190-e6dcf300-34ef-11eb-9cf5-cfde20b13a26.png)

The issue should be fixed when you update the datafiles folder ! :) I think, but let me know if you have problems with this because I was getting this for a really long time too!

Thanks,

Andrea

**Comment by tingyuw** [comment]
Thank you for the comment. datafiles folder is updated!
