### ISSUE TITLE
Definitions Section - Separating the words

### ISSUE THREAD

**Issue by andreamclemeno** [tingyuw/cas741#29]
Hi @tingyuw,

Last issue!! I think it would be good to separate the words in your definitions like instead of ForceEquilibrium changing it to Force Equilibrium. 

![image](https://user-images.githubusercontent.com/70977402/100961405-5521b580-34f0-11eb-874d-e7ded315f254.png)

Thanks,

Andrea

**Comment by tingyuw** [comment]
The problem is addressed. Thank you!
