### ISSUE TITLE
Data Constraints values and tolerance

### ISSUE THREAD

**Issue by machadotiagom** [tingyuw/cas741#31]
Hi @tingyuw 

In Data Constraints section, when you define the range value and tolerance, where does that information comes from? Is there any reference that you can point out to support your statement? or is this something that you are deciding by yourself as an engineer in a sort of previous analyses of the problem?

Tiago.

**Comment by tingyuw** [comment]
The software constraints are decided by me to prevent the input values being too large. Users can change the constraints as they wish. The reason for setting the data constraints is to clarify the environment and increase the maintainability.
