### ISSUE TITLE
Traceability Matrices and Graphs is empty

### ISSUE THREAD

**Issue by machadotiagom** [tingyuw/cas741#32]
Hi @tingyuw 

I noticed that Table "Traceability Matrices and Graphs" is empty. Is that correct? 

![image](https://user-images.githubusercontent.com/10463316/102537147-954c7080-4078-11eb-8b0a-6392fb9b97b2.png)

Tiago.

**Comment by tingyuw** [comment]
Right, this table is empty since there is no dependency between each assumption.
