### ISSUE TITLE
Ambiguity among input data software constraints. 

### ISSUE THREAD

**Issue by yanxuanm** [tingyuw/cas741#4]
Hi Ting-Yu, 

Thanks for letting me review your SRS. 

Solving statics of a truss often involving some classical physics knowledge, and Trigonometric functions. I think your document has detailed description of these requirements. 

But there are some ambiguity among input data software constraints, in page 10. It is unclear for me regarding those max and min values. 

Xuanming Yan

**Comment by tingyuw** [comment]
Hello @yanxuanm 
Thank you for the comment!
I forgot to include the information. The max and min values are now included and addressed with 3fe613beb9dca25a730a6f0cf47911c49521972b
