### ISSUE TITLE
Cross References between SRS and VnV

### ISSUE THREAD

**Issue by moalaa** [tingyuw/cas741#9]
@tingyuw,
I think you can enhance the cross references between SRS, and VnV. You can check 
[VnV of /SpectrumImageAnalysisPy](https://github.com/icbicket/SpectrumImageAnalysisPy/blob/master/Doc/TestPlan/TestPlan.pdf) You may find it useful.
Also, subsection 4.2.6  wasn't referenced correctly.

![issue11](https://user-images.githubusercontent.com/31176105/98154769-44efc980-1ea3-11eb-9897-94c2e4251873.PNG)
![issue1](https://user-images.githubusercontent.com/31176105/98154763-43260600-1ea3-11eb-9fa8-98eff97d6213.PNG)

**Comment by tingyuw** [comment]
I have addressed the cross references problem with 3bd08f8e00b7c217a4d466ded79496a3341bff90.
Thank you for the comment!
